### ISSUE TITLE
Missing the main files

### ISSUE THREAD

**Issue by anonymousAI88** [dxlong2000/CoHS-CQG#1]
Hello, I'm interested in executing your code. When do you anticipate releasing the main file?

**Comment by dxlong2000** [comment]
Hi, I'll update tomorrow, hold on, thanks for the question!

**Comment by anonymousAI88** [comment]
你好，你的邮件我已经收到，我会在第一时间查看并回复。

**Comment by dxlong2000** [comment]
Updated!
